# messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Messages
  #  messages client class.
  class Client
    attr_reader :config

    # Access to delivery_reports controller.
    # @return [DeliveryReportsController] Returns the controller instance.
    def delivery_reports
      @delivery_reports ||= DeliveryReportsController.new config
    end

    # Access to messages controller.
    # @return [MessagesController] Returns the controller instance.
    def messages
      @messages ||= MessagesController.new config
    end

    # Access to replies controller.
    # @return [RepliesController] Returns the controller instance.
    def replies
      @replies ||= RepliesController.new config
    end

    def initialize(connection: nil, adapter: :net_http_persistent, timeout: 60,
                   max_retries: 0, retry_interval: 1, backoff_factor: 2,
                   retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                   retry_methods: %i[get put],
                   environment: Environment::PRODUCTION,
                   basic_auth_user_name: 'TODO: Replace',
                   basic_auth_password: 'TODO: Replace', config: nil)
      @config = if config.nil?
                  Configuration.new(connection: connection, adapter: adapter,
                                    timeout: timeout, max_retries: max_retries,
                                    retry_interval: retry_interval,
                                    backoff_factor: backoff_factor,
                                    retry_statuses: retry_statuses,
                                    retry_methods: retry_methods,
                                    environment: environment,
                                    basic_auth_user_name: basic_auth_user_name,
                                    basic_auth_password: basic_auth_password)
                else
                  config
                end
    end
  end
end
