# message_media_messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MessageMediaMessages
  # CancelScheduledMessageRequest Model.
  class CancelScheduledMessageRequest < BaseModel
    # TODO: Write general description for this method
    # @return [String]
    attr_accessor :status

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['status'] = 'status'
      @_hash
    end

    def initialize(status = 'cancelled')
      @status = status
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      status = hash['status'] ||= 'cancelled'

      # Create object from extracted values.
      CancelScheduledMessageRequest.new(status)
    end
  end
end
