# message_media_messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MessageMediaMessages
  # CheckDeliveryReportsResponse Model.
  class CheckDeliveryReportsResponse < BaseModel
    # The oldest 100 unconfirmed delivery reports
    # @return [List of DeliveryReport]
    attr_accessor :delivery_reports

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['delivery_reports'] = 'delivery_reports'
      @_hash
    end

    def initialize(delivery_reports = nil)
      @delivery_reports = delivery_reports
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      delivery_reports = nil
      unless hash['delivery_reports'].nil?
        delivery_reports = []
        hash['delivery_reports'].each do |structure|
          delivery_reports << (DeliveryReport.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      CheckDeliveryReportsResponse.new(delivery_reports)
    end
  end
end
