# message_media_messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MessageMediaMessages
  # CheckRepliesResponse Model.
  class CheckRepliesResponse < BaseModel
    # The oldest 100 unconfirmed replies
    # @return [List of Reply]
    attr_accessor :replies

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['replies'] = 'replies'
      @_hash
    end

    def initialize(replies = nil)
      @replies = replies
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      # Parameter is an array, so we need to iterate through it
      replies = nil
      unless hash['replies'].nil?
        replies = []
        hash['replies'].each do |structure|
          replies << (Reply.from_hash(structure) if structure)
        end
      end

      # Create object from extracted values.
      CheckRepliesResponse.new(replies)
    end
  end
end
