# message_media_messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MessageMediaMessages
  # ConfirmDeliveryReportsAsReceivedRequest Model.
  class ConfirmDeliveryReportsAsReceivedRequest < BaseModel
    # TODO: Write general description for this method
    # @return [List of String]
    attr_accessor :delivery_report_ids

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['delivery_report_ids'] = 'delivery_report_ids'
      @_hash
    end

    def initialize(delivery_report_ids = nil)
      @delivery_report_ids = delivery_report_ids
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      delivery_report_ids = hash['delivery_report_ids']

      # Create object from extracted values.
      ConfirmDeliveryReportsAsReceivedRequest.new(delivery_report_ids)
    end
  end
end
