# message_media_messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require 'date'
module MessageMediaMessages
  # DeliveryReport Model.
  class DeliveryReport < BaseModel
    # The URL specified as the callback URL in the original submit message
    # request
    # @return [String]
    attr_accessor :callback_url

    # The date and time at which this delivery report was generated in UTC.
    # @return [DateTime]
    attr_accessor :date_received

    # Deprecated, no longer in use
    # @return [Integer]
    attr_accessor :delay

    # Unique ID for this delivery report
    # @return [UUID | String]
    attr_accessor :delivery_report_id

    # Unique ID of the original message
    # @return [UUID | String]
    attr_accessor :message_id

    # Any metadata that was included in the original submit message request
    # @return [Object]
    attr_accessor :metadata

    # Text of the original message.
    # @return [String]
    attr_accessor :original_text

    # Address from which this delivery report was received
    # @return [String]
    attr_accessor :source_number

    # The status of the message as per the delivery report
    # @return [Status2Enum]
    attr_accessor :status

    # The date and time when the message status changed in UTC. For a delivered
    # DR this may indicate the time at which the message was received on the
    # handset.
    # @return [DateTime]
    attr_accessor :submitted_date

    # The date and time when the message status changed in UTC. For a delivered
    # DR this may indicate the time at which the message was received on the
    # handset.
    # @return [VendorAccountId]
    attr_accessor :vendor_account_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['callback_url'] = 'callback_url'
      @_hash['date_received'] = 'date_received'
      @_hash['delay'] = 'delay'
      @_hash['delivery_report_id'] = 'delivery_report_id'
      @_hash['message_id'] = 'message_id'
      @_hash['metadata'] = 'metadata'
      @_hash['original_text'] = 'original_text'
      @_hash['source_number'] = 'source_number'
      @_hash['status'] = 'status'
      @_hash['submitted_date'] = 'submitted_date'
      @_hash['vendor_account_id'] = 'vendor_account_id'
      @_hash
    end

    def initialize(callback_url = nil,
                   date_received = nil,
                   delay = nil,
                   delivery_report_id = nil,
                   message_id = nil,
                   metadata = nil,
                   original_text = nil,
                   source_number = nil,
                   status = nil,
                   submitted_date = nil,
                   vendor_account_id = nil)
      @callback_url = callback_url
      @date_received = date_received
      @delay = delay
      @delivery_report_id = delivery_report_id
      @message_id = message_id
      @metadata = metadata
      @original_text = original_text
      @source_number = source_number
      @status = status
      @submitted_date = submitted_date
      @vendor_account_id = vendor_account_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      callback_url = hash['callback_url']
      date_received = APIHelper.rfc3339(hash['date_received']) if
        hash['date_received']
      delay = hash['delay']
      delivery_report_id = hash['delivery_report_id']
      message_id = hash['message_id']
      metadata = hash['metadata']
      original_text = hash['original_text']
      source_number = hash['source_number']
      status = hash['status']
      submitted_date = APIHelper.rfc3339(hash['submitted_date']) if
        hash['submitted_date']
      if hash['vendor_account_id']
        vendor_account_id = VendorAccountId.from_hash(hash['vendor_account_id'])
      end

      # Create object from extracted values.
      DeliveryReport.new(callback_url,
                         date_received,
                         delay,
                         delivery_report_id,
                         message_id,
                         metadata,
                         original_text,
                         source_number,
                         status,
                         submitted_date,
                         vendor_account_id)
    end
  end
end
