# message_media_messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MessageMediaMessages
  # Format.
  class FormatEnum
    FORMAT_ENUM = [
      # TODO: Write general description for SMS
      SMS = 'SMS'.freeze,

      # TODO: Write general description for TTS
      TTS = 'TTS'.freeze,

      # TODO: Write general description for MMS
      MMS = 'MMS'.freeze
    ].freeze
  end
end
