# message_media_messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MessageMediaMessages
  # The status of the message as per the delivery report
  class Status2Enum
    STATUS2_ENUM = [
      # TODO: Write general description for ENROUTE
      ENROUTE = 'enroute'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze,

      # TODO: Write general description for SUBMITTED
      SUBMITTED = 'submitted'.freeze,

      # TODO: Write general description for DELIVERED
      DELIVERED = 'delivered'.freeze,

      # TODO: Write general description for EXPIRED
      EXPIRED = 'expired'.freeze,

      # TODO: Write general description for REJECTED
      REJECTED = 'rejected'.freeze,

      # TODO: Write general description for UNDELIVERABLE
      UNDELIVERABLE = 'undeliverable'.freeze
    ].freeze
  end
end
