# message_media_messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module MessageMediaMessages
  # The status of the message
  class StatusEnum
    STATUS_ENUM = [
      # TODO: Write general description for ENROUTE
      ENROUTE = 'enroute'.freeze,

      # TODO: Write general description for SUBMITTED
      SUBMITTED = 'submitted'.freeze,

      # TODO: Write general description for DELIVERED
      DELIVERED = 'delivered'.freeze,

      # TODO: Write general description for EXPIRED
      EXPIRED = 'expired'.freeze,

      # TODO: Write general description for REJECTED
      REJECTED = 'rejected'.freeze,

      # TODO: Write general description for UNDELIVERABLE
      UNDELIVERABLE = 'undeliverable'.freeze,

      # TODO: Write general description for QUEUED
      QUEUED = 'queued'.freeze,

      # TODO: Write general description for PROCESSED
      PROCESSED = 'processed'.freeze,

      # TODO: Write general description for CANCELLED
      CANCELLED = 'cancelled'.freeze,

      # TODO: Write general description for SCHEDULED
      SCHEDULED = 'scheduled'.freeze,

      # TODO: Write general description for FAILED
      FAILED = 'failed'.freeze
    ].freeze
  end
end
