# messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Messages
  # CheckRepliesResponse Model.
  class CheckRepliesResponse < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [List of Object]
    attr_accessor :replies

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['replies'] = 'replies'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(replies = nil)
      @replies = replies
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      replies = hash.key?('replies') ? hash['replies'] : nil

      # Create object from extracted values.
      CheckRepliesResponse.new(replies)
    end
  end
end
