# messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Messages
  # SourceNumberType.
  class SourceNumberTypeEnum
    SOURCE_NUMBER_TYPE_ENUM = [
      # TODO: Write general description for INTERNATIONAL
      INTERNATIONAL = 'INTERNATIONAL'.freeze,

      # TODO: Write general description for ALPHANUMERIC
      ALPHANUMERIC = 'ALPHANUMERIC'.freeze,

      # TODO: Write general description for SHORTCODE
      SHORTCODE = 'SHORTCODE'.freeze
    ].freeze
  end
end
