# messages
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module Messages
  # BaseController.
  class BaseController
    attr_accessor :config, :http_call_back

    def initialize(config, http_call_back: nil)
      @config = config
      @http_call_back = http_call_back

      @global_headers = {
        'user-agent' => get_user_agent
      }
    end

    def validate_parameters(args)
      args.each do |_name, value|
        raise ArgumentError, "Required parameter #{_name} cannot be nil." if value.nil?
      end
    end

    def validate_parameters_types(args)
      args.each do |_name, type|
        key, val = type.first
        APIHelper.validate_types(key, val) unless key.nil?
      end
    end

    def execute_request(request, binary: false)
      @http_call_back&.on_before_request(request)

      APIHelper.clean_hash(request.headers)
      request.headers.merge!(@global_headers)

      response = if binary
                   config.http_client.execute_as_binary(request)
                 else
                   config.http_client.execute_as_string(request)
                 end
      @http_call_back&.on_after_response(response)

      response
    end

    def validate_response(response)
      case response.status_code
      when 402
        raise APIException.new(
          'The feature that you are trying to use is disabled by default. Please ' \
        'contact tech support at support@messagemedia.com.au',
          response
        )
      when 404
        raise APIException.new(
          'The specified resource does not exist.',
          response
        )
      end
      raise APIException.new 'HTTP Response Not OK', response unless
        response.status_code.between?(200, 208) # [200,208] = HTTP OK
    end

    def get_user_agent
      user_agent = 'APIMATIC 3.0'
      user_agent
    end
  end
end
